<?php

use Illuminate\Database\Seeder;

class MatchEquipeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('MatchEquipe')->insert([

            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '1', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Internazionale'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '2', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Lyon'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '3', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Napoli'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '4', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Salzburg'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '5', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Dortmund'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '6', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Benfica'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '7', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Chelsea'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '8', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Ajax'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '9', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Club Brugge'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '10', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Olympiacos'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '11', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Paris'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '12', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Bayern'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '13', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Dinamo Zagreb'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '14', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Shakhtar Donetsk'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '15', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Leverkusen'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '16', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Atlético'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '17', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Real Madrid'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '18', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Atalanta'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '19', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Galatasaray'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '20', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Tottenham'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '21', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Crvena zvezda'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '22', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Man. City'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '23', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Juventus'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '24', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Lokomotiv Moskva'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '25', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Genk'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '26', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Slavia Praha'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '27', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Liverpool'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '28', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Barcelona'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '29', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Leipzig'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '30', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Zenit'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '31', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('LOSC'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '32', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Valencia'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '33', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Shakhtar Donetsk'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '34', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Atlético'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '35', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Club Brugge'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '36', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Galatasaray'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '37', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Olympiacos'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '38', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Tottenham'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '39', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Man. City'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '40', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Juventus'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '41', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Leipzig'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '42', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Ajax'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '43', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Salzburg'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '44', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Genk'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '45', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Internazionale'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '46', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Slavia Praha'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '47', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Benfica'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '48', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('LOSC'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '49', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Barcelona'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '50', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Zenit'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '51', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Napoli'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '52', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Liverpool'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '53', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Dortmund'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '54', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Lyon'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '55', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Chelsea'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '56', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Valencia'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '57', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Bayern'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '58', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Lokomotiv Moskva'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '59', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Paris'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '60', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Real Madrid'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '61', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Crvena zvezda'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '62', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Dinamo Zagreb'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '63', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Atalanta'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '64', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Leverkusen'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '65', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Galatasaray'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '66', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Lokomotiv Moskva'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '67', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Real Madrid'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '68', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Crvena zvezda'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '69', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Tottenham'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '70', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Atalanta'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '71', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Man. City'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '72', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Juventus'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '73', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Zenit'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '74', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Valencia'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '75', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Liverpool'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '76', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Genk'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '77', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Barcelona'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '78', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Slavia Praha'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '79', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Leipzig'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '80', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('LOSC'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '81', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Napoli'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '82', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Salzburg'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '83', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Dortmund'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '84', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Internazionale'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '85', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Lyon'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '86', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Benfica'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '87', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Chelsea'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '88', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Ajax'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '89', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Dinamo Zagreb'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '90', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Shakhtar Donetsk'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '91', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Paris'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '92', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Club Brugge'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '93', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Bayern'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '94', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Olympiacos'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '95', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Leverkusen'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '96', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Atlético'), 'DomExt' => 'D', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '1', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Slavia Praha'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '2', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Zenit'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '3', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Liverpool'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '4', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Genk'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '5', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Barcelona'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '6', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Leipzig'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '7', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('Valencia'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '8', '2019-09-17'), 'Equipe_Idt' => App\Equipe::GetIdt('LOSC'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '9', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Galatasaray'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '10', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Tottenham'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '11', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Real Madrid'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '12', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Crvena zvezda'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '13', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Atalanta'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '14', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Man. City'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '15', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Lokomotiv Moskva'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '16', '2019-09-18'), 'Equipe_Idt' => App\Equipe::GetIdt('Juventus'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '17', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Club Brugge'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '18', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Shakhtar Donetsk'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '19', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Paris'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '20', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Bayern'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '21', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Olympiacos'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '22', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Dinamo Zagreb'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '23', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Leverkusen'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '24', '2019-10-01'), 'Equipe_Idt' => App\Equipe::GetIdt('Atlético'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '25', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Napoli'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '26', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Dortmund'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '27', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Salzburg'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '28', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Internazionale'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '29', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Lyon'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '30', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Benfica'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '31', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Chelsea'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '32', '2019-10-02'), 'Equipe_Idt' => App\Equipe::GetIdt('Ajax'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '33', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Dinamo Zagreb'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '34', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Leverkusen'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '35', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Paris'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '36', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Real Madrid'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '37', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Bayern'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '38', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Crvena zvezda'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '39', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Atalanta'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '40', '2019-10-22'), 'Equipe_Idt' => App\Equipe::GetIdt('Lokomotiv Moskva'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '41', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Zenit'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '42', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Chelsea'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '43', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Napoli'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '44', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Liverpool'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '45', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Dortmund'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '46', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Barcelona'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '47', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Lyon'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '48', '2019-10-23'), 'Equipe_Idt' => App\Equipe::GetIdt('Valencia'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '49', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Slavia Praha'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '50', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Leipzig'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '51', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Salzburg'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '52', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Genk'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '53', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Internazionale'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '54', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Benfica'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '55', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('Ajax'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '56', '2019-11-05'), 'Equipe_Idt' => App\Equipe::GetIdt('LOSC'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '57', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Olympiacos'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '58', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Juventus'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '59', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Club Brugge'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '60', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Galatasaray'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '61', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Tottenham'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '62', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Shakhtar Donetsk'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '63', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Man. City'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '64', '2019-11-06'), 'Equipe_Idt' => App\Equipe::GetIdt('Atlético'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '65', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Club Brugge'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '66', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Leverkusen'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '67', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Paris'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '68', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Bayern'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '69', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Olympiacos'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '70', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Dinamo Zagreb'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '71', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Shakhtar Donetsk'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '72', '2019-11-26'), 'Equipe_Idt' => App\Equipe::GetIdt('Atlético'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '73', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Lyon'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '74', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Chelsea'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '75', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Napoli'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '76', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Salzburg'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '77', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Dortmund'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '78', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Internazionale'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '79', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Benfica'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '80', '2019-11-27'), 'Equipe_Idt' => App\Equipe::GetIdt('Ajax'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '81', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Genk'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '82', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Liverpool'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '83', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Slavia Praha'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '84', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Barcelona'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '85', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Leipzig'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '86', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Zenit'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '87', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('LOSC'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '88', '2019-12-10'), 'Equipe_Idt' => App\Equipe::GetIdt('Valencia'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '89', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Man. City'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '90', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Atalanta'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '91', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Galatasaray'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '92', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Real Madrid'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '93', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Tottenham'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '94', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Crvena zvezda'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '95', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Juventus'), 'DomExt' => 'E', ],
            ['Match_Idt' => App\Match::GetIdt('UEFACL', '66', '96', '2019-12-11'), 'Equipe_Idt' => App\Equipe::GetIdt('Lokomotiv Moskva'), 'DomExt' => 'E', ],

        ]);
    }
}
