<?php

use Illuminate\Database\Seeder;

class NationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('nation')->insert([
            ['cod' => 'AFG', 'lib' => 'Afghanistan'],
            ['cod' => 'NZL', 'lib' => 'New Zealand',],
            ['cod' => 'NCA', 'lib' => 'Nicaragua',],
            ['cod' => 'NIG', 'lib' => 'Niger',],
            ['cod' => 'NGA', 'lib' => 'Nigeria',],
            ['cod' => 'PRK', 'lib' => 'North Korea',],
            ['cod' => 'NIR', 'lib' => 'Northern Ireland',],
            ['cod' => 'NOR', 'lib' => 'Norway',],
            ['cod' => 'OMA', 'lib' => 'Oman',],
            ['cod' => 'PAK', 'lib' => 'Pakistan',],
            ['cod' => 'PLE', 'lib' => 'Palestine',],
            ['cod' => 'NCL', 'lib' => 'New Caledonia',],
            ['cod' => 'PAN', 'lib' => 'Panama',],
            ['cod' => 'PAR', 'lib' => 'Paraguay',],
            ['cod' => 'PER', 'lib' => 'Peru',],
            ['cod' => 'PHI', 'lib' => 'Philippines',],
            ['cod' => 'POL', 'lib' => 'Poland',],
            ['cod' => 'POR', 'lib' => 'Portugal',],
            ['cod' => 'PUR', 'lib' => 'Puerto Rico',],
            ['cod' => 'QAT', 'lib' => 'Qatar',],
            ['cod' => 'IRL', 'lib' => 'Republic of Ireland',],
            ['cod' => 'ROU', 'lib' => 'Romania',],
            ['cod' => 'RUS', 'lib' => 'Russia',],
            ['cod' => 'PNG', 'lib' => 'Papua New Guinea',],
            ['cod' => 'NED', 'lib' => 'Netherlands',],
            ['cod' => 'NEP', 'lib' => 'Nepal',],
            ['cod' => 'NAM', 'lib' => 'Namibia',],
            ['cod' => 'LBR', 'lib' => 'Liberia',],
            ['cod' => 'LBY', 'lib' => 'Libya',],
            ['cod' => 'LIE', 'lib' => 'Liechtenstein',],
            ['cod' => 'LTU', 'lib' => 'Lithuania',],
            ['cod' => 'LUX', 'lib' => 'Luxembourg',],
            ['cod' => 'MAC', 'lib' => 'Macau',],
            ['cod' => 'MKD', 'lib' => 'Macedonia',],
            ['cod' => 'MAD', 'lib' => 'Madagascar',],
            ['cod' => 'MWI', 'lib' => 'Malawi',],
            ['cod' => 'MAS', 'lib' => 'Malaysia',],
            ['cod' => 'MDV', 'lib' => 'Maldives',],
            ['cod' => 'MLI', 'lib' => 'Mali',],
            ['cod' => 'MLT', 'lib' => 'Malta',],
            ['cod' => 'MTN', 'lib' => 'Mauritania',],
            ['cod' => 'MRI', 'lib' => 'Mauritius',],
            ['cod' => 'MEX', 'lib' => 'Mexico',],
            ['cod' => 'MDA', 'lib' => 'Moldova',],
            ['cod' => 'MNG', 'lib' => 'Mongolia',],
            ['cod' => 'MNE', 'lib' => 'Montenegro',],
            ['cod' => 'MSR', 'lib' => 'Montserrat',],
            ['cod' => 'MAR', 'lib' => 'Morocco',],
            ['cod' => 'MOZ', 'lib' => 'Mozambique',],
            ['cod' => 'MYA', 'lib' => 'Myanmar',],
            ['cod' => 'RWA', 'lib' => 'Rwanda',],
            ['cod' => 'LES', 'lib' => 'Lesotho',],
            ['cod' => 'SKN', 'lib' => 'Saint Kitts and Nevis',],
            ['cod' => 'VIN', 'lib' => 'Saint Vincent and the Grenadines',],
            ['cod' => 'TAN', 'lib' => 'Tanzania',],
            ['cod' => 'THA', 'lib' => 'Thailand',],
            ['cod' => 'TLS', 'lib' => 'Timor-Leste',],
            ['cod' => 'TOG', 'lib' => 'Togo',],
            ['cod' => 'TGA', 'lib' => 'Tonga',],
            ['cod' => 'TRI', 'lib' => 'Trinidad and Tobago',],
            ['cod' => 'TUN', 'lib' => 'Tunisia',],
            ['cod' => 'TUR', 'lib' => 'Turkey',],
            ['cod' => 'TKM', 'lib' => 'Turkmenistan',],
            ['cod' => 'TCA', 'lib' => 'Turks and Caicos Islands',],
            ['cod' => 'TJK', 'lib' => 'Tajikistan',],
            ['cod' => 'UGA', 'lib' => 'Uganda',],
            ['cod' => 'UAE', 'lib' => 'United Arab Emirates',],
            ['cod' => 'USA', 'lib' => 'United States',],
            ['cod' => 'URU', 'lib' => 'Uruguay',],
            ['cod' => 'VIR', 'lib' => 'U.S. Virgin Islands',],
            ['cod' => 'UZB', 'lib' => 'Uzbekistan',],
            ['cod' => 'VAN', 'lib' => 'Vanuatu',],
            ['cod' => 'VEN', 'lib' => 'Venezuela',],
            ['cod' => 'VIE', 'lib' => 'Vietnam',],
            ['cod' => 'WAL', 'lib' => 'Wales',],
            ['cod' => 'YEM', 'lib' => 'Yemen',],
            ['cod' => 'UKR', 'lib' => 'Ukraine',],
            ['cod' => 'TAH', 'lib' => 'Tahiti',],
            ['cod' => 'SYR', 'lib' => 'Syria',],
            ['cod' => 'SUI', 'lib' => 'Switzerland',],
            ['cod' => 'SAM', 'lib' => 'Samoa',],
            ['cod' => 'SMR', 'lib' => 'San Marino',],
            ['cod' => 'STP', 'lib' => 'São Tomé and Príncipe',],
            ['cod' => 'KSA', 'lib' => 'Saudi Arabia',],
            ['cod' => 'SCO', 'lib' => 'Scotland',],
            ['cod' => 'SEN', 'lib' => 'Senegal',],
            ['cod' => 'SRB', 'lib' => 'Serbia',],
            ['cod' => 'SEY', 'lib' => 'Seychelles',],
            ['cod' => 'SLE', 'lib' => 'Sierra Leone',],
            ['cod' => 'SIN', 'lib' => 'Singapore',],
            ['cod' => 'SVK', 'lib' => 'Slovakia',],
            ['cod' => 'SVN', 'lib' => 'Slovenia',],
            ['cod' => 'SOL', 'lib' => 'Solomon Islands',],
            ['cod' => 'SOM', 'lib' => 'Somalia',],
            ['cod' => 'RSA', 'lib' => 'South Africa',],
            ['cod' => 'KOR', 'lib' => 'South Korea',],
            ['cod' => 'SSD', 'lib' => 'South Sudan',],
            ['cod' => 'ESP', 'lib' => 'Spain',],
            ['cod' => 'SRI', 'lib' => 'Sri Lanka',],
            ['cod' => 'SDN', 'lib' => 'Sudan',],
            ['cod' => 'SUR', 'lib' => 'Suriname',],
            ['cod' => 'SWZ', 'lib' => 'Swaziland',],
            ['cod' => 'SWE', 'lib' => 'Sweden',],
            ['cod' => 'LCA', 'lib' => 'Saint Lucia',],
            ['cod' => 'ZAM', 'lib' => 'Zambia',],
            ['cod' => 'LIB', 'lib' => 'Lebanon',],
            ['cod' => 'LAO', 'lib' => 'Laos',],
            ['cod' => 'VGB', 'lib' => 'British Virgin Islands',],
            ['cod' => 'BRU', 'lib' => 'Brunei',],
            ['cod' => 'BUL', 'lib' => 'Bulgaria',],
            ['cod' => 'BFA', 'lib' => 'Burkina Faso',],
            ['cod' => 'BDI', 'lib' => 'Burundi',],
            ['cod' => 'CAM', 'lib' => 'Cambodia',],
            ['cod' => 'CMR', 'lib' => 'Cameroon',],
            ['cod' => 'CAN', 'lib' => 'Canada',],
            ['cod' => 'CPV', 'lib' => 'Cape Verde',],
            ['cod' => 'CAY', 'lib' => 'Cayman Islands',],
            ['cod' => 'BRA', 'lib' => 'Brazil',],
            ['cod' => 'CTA', 'lib' => 'Central African Republic',],
            ['cod' => 'CHI', 'lib' => 'Chile',],
            ['cod' => 'CHN', 'lib' => 'China PR',],
            ['cod' => 'TPE', 'lib' => 'Chinese Taipei',],
            ['cod' => 'COL', 'lib' => 'Colombia',],
            ['cod' => 'COM', 'lib' => 'Comoros',],
            ['cod' => 'CGO', 'lib' => 'Congo',],
            ['cod' => 'COK', 'lib' => 'Cook Islands',],
            ['cod' => 'CRC', 'lib' => 'Costa Rica',],
            ['cod' => 'CRO', 'lib' => 'Croatia',],
            ['cod' => 'CUB', 'lib' => 'Cuba',],
            ['cod' => 'CHA', 'lib' => 'Chad',],
            ['cod' => 'BOT', 'lib' => 'Botswana',],
            ['cod' => 'BIH', 'lib' => 'Bosnia and Herzegovina',],
            ['cod' => 'BOL', 'lib' => 'Bolivia',],
            ['cod' => 'ALB', 'lib' => 'Albania',],
            ['cod' => 'ALG', 'lib' => 'Algeria',],
            ['cod' => 'ASA', 'lib' => 'American Samoa',],
            ['cod' => 'AND', 'lib' => 'Andorra',],
            ['cod' => 'ANG', 'lib' => 'Angola',],
            ['cod' => 'AIA', 'lib' => 'Anguilla',],
            ['cod' => 'ATG', 'lib' => 'Antigua and Barbuda',],
            ['cod' => 'ARG', 'lib' => 'Argentina',],
            ['cod' => 'ARM', 'lib' => 'Armenia',],
            ['cod' => 'ARU', 'lib' => 'Aruba',],
            ['cod' => 'AUS', 'lib' => 'Australia',],
            ['cod' => 'AUT', 'lib' => 'Austria',],
            ['cod' => 'AZE', 'lib' => 'Azerbaijan',],
            ['cod' => 'BAH', 'lib' => 'Bahamas',],
            ['cod' => 'BHR', 'lib' => 'Bahrain',],
            ['cod' => 'BAN', 'lib' => 'Bangladesh',],
            ['cod' => 'BRB', 'lib' => 'Barbados',],
            ['cod' => 'BLR', 'lib' => 'Belarus',],
            ['cod' => 'BEL', 'lib' => 'Belgium',],
            ['cod' => 'BLZ', 'lib' => 'Belize',],
            ['cod' => 'BEN', 'lib' => 'Benin',],
            ['cod' => 'BER', 'lib' => 'Bermuda',],
            ['cod' => 'BHU', 'lib' => 'Bhutan',],
            ['cod' => 'CUW', 'lib' => 'Curaçao',],
            ['cod' => 'LVA', 'lib' => 'Latvia',],
            ['cod' => 'CYP', 'lib' => 'Cyprus',],
            ['cod' => 'DEN', 'lib' => 'Denmark',],
            ['cod' => 'GNB', 'lib' => 'Guinea-Bissau',],
            ['cod' => 'GUY', 'lib' => 'Guyana',],
            ['cod' => 'HAI', 'lib' => 'Haiti',],
            ['cod' => 'HON', 'lib' => 'Honduras',],
            ['cod' => 'HKG', 'lib' => 'Hong Kong',],
            ['cod' => 'HUN', 'lib' => 'Hungary',],
            ['cod' => 'ISL', 'lib' => 'Iceland',],
            ['cod' => 'IND', 'lib' => 'India',],
            ['cod' => 'IDN', 'lib' => 'Indonesia',],
            ['cod' => 'IRN', 'lib' => 'Iran',],
            ['cod' => 'GUI', 'lib' => 'Guinea',],
            ['cod' => 'IRQ', 'lib' => 'Iraq',],
            ['cod' => 'ITA', 'lib' => 'Italy',],
            ['cod' => 'CIV', 'lib' => 'Ivory Coast',],
            ['cod' => 'JAM', 'lib' => 'Jamaica',],
            ['cod' => 'JPN', 'lib' => 'Japan',],
            ['cod' => 'JOR', 'lib' => 'Jordan',],
            ['cod' => 'KAZ', 'lib' => 'Kazakhstan',],
            ['cod' => 'KEN', 'lib' => 'Kenya',],
            ['cod' => 'KVX', 'lib' => 'Kosovo',],
            ['cod' => 'KUW', 'lib' => 'Kuwait',],
            ['cod' => 'KGZ', 'lib' => 'Kyrgyzstan',],
            ['cod' => 'ISR', 'lib' => 'Israel',],
            ['cod' => 'GUA', 'lib' => 'Guatemala',],
            ['cod' => 'GUM', 'lib' => 'Guam',],
            ['cod' => 'GRN', 'lib' => 'Grenada',],
            ['cod' => 'DJI', 'lib' => 'Djibouti',],
            ['cod' => 'DMA', 'lib' => 'Dominica',],
            ['cod' => 'DOM', 'lib' => 'Dominican Republic',],
            ['cod' => 'COD', 'lib' => 'DR Congo',],
            ['cod' => 'ECU', 'lib' => 'Ecuador',],
            ['cod' => 'EGY', 'lib' => 'Egypt',],
            ['cod' => 'SLV', 'lib' => 'El Salvador',],
            ['cod' => 'ENG', 'lib' => 'England',],
            ['cod' => 'EQG', 'lib' => 'Equatorial Guinea',],
            ['cod' => 'ERI', 'lib' => 'Eritrea',],
            ['cod' => 'EST', 'lib' => 'Estonia',],
            ['cod' => 'ETH', 'lib' => 'Ethiopia',],
            ['cod' => 'FRO', 'lib' => 'Faroe Islands',],
            ['cod' => 'FIJ', 'lib' => 'Fiji',],
            ['cod' => 'FIN', 'lib' => 'Finland',],
            ['cod' => 'FRA', 'lib' => 'France',],
            ['cod' => 'GAB', 'lib' => 'Gabon',],
            ['cod' => 'GAM', 'lib' => 'Gambia',],
            ['cod' => 'GEO', 'lib' => 'Georgia',],
            ['cod' => 'GER', 'lib' => 'Germany',],
            ['cod' => 'GHA', 'lib' => 'Ghana',],
            ['cod' => 'GIB', 'lib' => 'Gibraltar',],
            ['cod' => 'GRE', 'lib' => 'Greece',],
            ['cod' => 'CZE', 'lib' => 'Czech Republic',],
            ['cod' => 'ZIM', 'lib' => 'Zimbabwe',],
        ]);
    }
}
